steps:
  - label: ':webpack: Bundle size'
    command: './bundle_size.sh ${BUILD_IMAGE} ${PROJECT}'
    timeout_in_minutes: 15
    agents:
      queue: web-code-default
  - label: ':jest: Unit tests'
    command: './cover.sh ${BUILD_IMAGE} ${PROJECT}'
    timeout_in_minutes: 15
    agents:
      queue: web-code-default
  - label: ':flowtype: Flow'
    command: './flow.sh ${BUILD_IMAGE} ${PROJECT}'
    timeout_in_minutes: 15
    agents:
      queue: web-code-default
  - label: ':chrome: Integration tests'
    command: './integration ${BUILD_IMAGE_INTEGRATION} ${PROJECT}'
    timeout_in_minutes: 15
    agents:
      queue: web-code-default
  - label: ':eslint: Lint'
    command: './lint.sh ${BUILD_IMAGE} ${PROJECT}'
    timeout_in_minutes: 15
    agents:
      queue: web-code-default
