steps:
  - label: ':webpack: Bundle size'
    command: './bundle_size.sh'
    timeout_in_minutes: 15
    agents:
      queue: web-code-default
  - label: ':jest: Unit tests'
    command: './cover.sh'
    timeout_in_minutes: 15
    agents:
      queue: web-code-default
  - label: ':flowtype: Flow'
    command: './flow.sh'
    timeout_in_minutes: 15
    agents:
      queue: web-code-default
  - label: ':chrome: Integration tests'
    command: './integration.sh'
    timeout_in_minutes: 15
    agents:
      queue: web-code-default
  - label: ':eslint: Lint'
    command: './lint.sh'
    timeout_in_minutes: 15
    agents:
      queue: web-code-default
