steps:
  - name: ":console:"
    command: "./lint.sh"
    parallelism: 30
    agents:
      queue: web-code-default
  - name: ":console:"
    command: "./cover.sh"
    parallelism: 30
    agents:
      queue: web-code-default
  - name: ":console:"
    command: "./flow.sh"
    parallelism: 30
    agents:
      queue: web-code-default
  - wait
  - command: 'echo DONE'
    agents:
      queue: web-code-default