steps:
  - name: ":console:"
    command: "./lint.sh projects/example-trips-viewer-fusion"
    parallelism: 30
    agents:
      queue: web-code-default
  - name: ":console:"
    command: "./cover.sh projects/example-trips-viewer-fusion"
    parallelism: 30
    agents:
      queue: web-code-default
  - name: ":console:"
    command: "./flow.sh projects/example-trips-viewer-fusion"
    parallelism: 30
    agents:
      queue: web-code-default
  - wait
  - command: 'echo DONE'
    agents:
      queue: web-code-default